name: Build and Push IOPaint to GHCR Public

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout IOPaint Repository
        uses: actions/checkout@v4
        with:
          repository: 'Sanster/IOPaint'
          ref: 'main'

      - name: Rewrite CPUDockerfile
        run: |
          cat << 'EOF' > ./docker/CPUDockerfile
          FROM python:3.10-slim-bookworm

          RUN apt-get update && apt-get install -y --no-install-recommends \
              software-properties-common \
              libsm6 libxext6 ffmpeg libfontconfig1 libxrender1 libgl1-mesa-glx \
              curl gcc build-essential \
              && rm -rf /var/lib/apt/lists/*

          RUN pip install --no-cache-dir iopaint
          RUN iopaint install-plugins-packages

          EXPOSE 8080
          CMD ["iopaint", "start", "--model=lama", "--device=cpu", "--port=8080", "--host=0.0.0.0"]
          EOF

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/CPUDockerfile
          push: true
          # 打标为你的 GitHub 账号下的镜像名称
          tags: ghcr.io/${{ github.repository_owner }}/iopaint:latest
