name: Sync Docker Image to Tencent CCR

on:
  workflow_dispatch: # 支持手动点击按钮触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Tencent CCR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.TENCENT_REGISTRY }}
          username: ${{ secrets.TENCENT_USERNAME }}
          password: ${{ secrets.TENCENT_PASSWORD }}

      - name: Pull and Push IOPaint Image
        run: |
          # 1. 在海外服务器拉取 Docker Hub 官方镜像
          docker pull sanster/iopaint:latest
          
          # 2. 修改镜像 Tag 为你的腾讯云私有仓库地址 (将 myiopaint 改成你的命名空间)
          docker tag sanster/iopaint:latest ccr.ccs.tencentyun.com/myiopaint/iopaint:latest
          
          # 3. 推送到腾讯云
          docker push ccr.ccs.tencentyun.com/myiopaint/iopaint:latest
