name: Sync Docker Image to Tencent CCR

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. 登录 GitHub 镜像仓库（解决 ghcr.io denied 权限问题）
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 2. 登录腾讯云镜像仓库
      - name: Login to Tencent CCR
        uses: docker/login-action@v3
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_USERNAME }}
          password: ${{ secrets.TENCENT_PASSWORD }}

      # 3. 执行拉取与推送
      - name: Pull and Push IOPaint Image
        run: |
          docker pull ghcr.io/sanster/iopaint:latest
          docker tag ghcr.io/sanster/iopaint:latest ccr.ccs.tencentyun.com/myiopaint/iopaint:latest
          docker push ccr.ccs.tencentyun.com/myiopaint/iopaint:latest
